#!/usr/bin/ruby -w
#
# credit: http://www.kitebird.com/articles/ruby-mysql.html
#

#   tunnel_cmd = %Q(
#     ssh -N -L 3311:smf1-acl-35-sr1.prod.twitter.com:3306 -o StrictHostKeyChecking=no nest2.corp.twitter.com
#   )
#   system(tunnel_cmd)

require 'rubygems'
require "mysql"

def setup_tunnel
  #
  # NOTE: use quote but NOT %Q...
  #       because %Q increments the tunnel_cmd pid by 1
  #       weird...
   tunnel_cmd = "ssh -N -L 3311:smf1-acl-35-sr1.prod.twitter.com:3306 -o StrictHostKeyChecking=no nest2.corp.twitter.com"
   pipe = IO.popen(tunnel_cmd)
   puts "setup pipe pid: #{pipe.pid}"
   sleep 1
   system("nc -z localhost 3311")
   if $?.exitstatus == 0
     puts "nc says port is open"
   else
     puts "nc says port is NOT open"
     exit 1
   end
   pipe
end

def close_tunnel(pipe)
  puts "close pipe pid: #{pipe.pid}"
  if pipe.pid
    Process.kill 'TERM', pipe.pid
  end
  pipe.close
end

pipe = setup_tunnel

begin
  # connect to the MySQL server
  # use real user, pwd, db when run
     dbh = Mysql::new("127.0.0.1", "<user>", "<pwd>", "<db>", 3311)
     # get server version string and display it
     puts "Server version: " + dbh.get_server_info
   rescue Mysql::Error => e
     puts "Error code: #{e.errno}"
     puts "Error message: #{e.error}"
     puts "Error SQLSTATE: #{e.sqlstate}" if e.respond_to?("sqlstate")
   ensure
     # disconnect from server
#     dbh.close if dbh
end

puts "connected..."
puts


stmt = %q(SELECT  branch_name  from pellets where preflight_status = 'locked')

res = dbh.query(stmt)

branches = []
while row = res.fetch_row do
#  puts row[0],
  branches << row[0]
end

puts branches.join(',')
puts
puts branches.size

close_tunnel(pipe)

puts "current process id: #{$$}"

